name: Unity License Finder
on: [push, workflow_dispatch]
jobs:
  get_license:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate ALF
        run: |
          docker run --rm \
          -v "$(pwd):/project" \
          unityci/editor:ubuntu-2022.3.62f2-android-3.1.0 \
          unity-editor \
          -batchmode \
          -nographics \
          -createManualActivationFile \
          -logfile /dev/stdout

      - name: Inspect Logs
        run: ls -R
        
