name: Generate Unity Activation File
on: [push, workflow_dispatch]
jobs:
  get_alf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Request Manual Activation File
        uses: game-ci/unity-request-activation-file@v2
        with:
          unityVersion: 2022.3.62f2

      - name: Upload Activation File
        uses: actions/upload-artifact@v4
        with:
          name: Unity-Activation-File
          path: ./*.alf
          
