name: Get Unity License File
on: [push, workflow_dispatch]
jobs:
  get_license:
    runs-on: ubuntu-latest
    steps:
      - name: Free Space
        run: sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc

      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate ALF
        run: |
          docker run --rm \
          -v "$(pwd):/project" \
          unityci/editor:ubuntu-2022.3.62f2-android-3.1.0 \
          unity-editor \
          -batchmode \
          -nographics \
          -createManualActivationFile \
          -logfile /dev/stdout
          
          # البحث عن الملف ونسخه لمجلد المشروع ليتم رفعه
          sudo find / -name "*.alf" -exec cp {} . \;

      - name: Upload ALF
        uses: actions/upload-artifact@v4
        with:
          name: Unity-Activation-File
          path: ./*.alf
          
